import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { ArrowRight, CheckCircle2, Compass, History, Loader2, Sparkles, Waypoints } from "lucide-react";
import { ReportActions } from "@/components/ReportActions";

type PathStep = { title: string; timeline: string; skills: string[]; description: string };
type CareerPath = { name: string; steps: PathStep[]; probability: string };
type CareerResult = { paths: CareerPath[]; recommendedPath: number; keyInsights: string[] };
function safeParse<T>(value: string | null): T | null { if (!value) return null; try { return JSON.parse(value) as T; } catch { return null; } }

export default function CareerPathPlanner() {
  const [targetRole, setTargetRole] = useState("");
  const [resumeContent, setResumeContent] = useState("");
  const [result, setResult] = useState<CareerResult | null>(null);
  const [activeTab, setActiveTab] = useState("planner");
  const historyQuery = trpc.careerPath.history.useQuery();
  const predictMutation = trpc.careerPath.predict.useMutation({
    onSuccess: (data) => { setResult(data as CareerResult); toast.success("Career paths generated."); void historyQuery.refetch(); },
    onError: (error) => toast.error(error.message || "Could not generate career paths."),
  });
  const predict = () => {
    if (targetRole.trim().length < 2) { toast.error("Enter a target role first."); return; }
    if (resumeContent.trim().length < 50) { toast.error("Paste at least 50 characters of resume content."); return; }
    predictMutation.mutate({ targetRole: targetRole.trim(), resumeContent: resumeContent.trim() });
  };

  return <div className="space-y-6">
    <div className="relative overflow-hidden rounded-2xl border border-pink/20 bg-pink/5 p-5 sm:p-6"><div className="aurora-orb aurora-orb-pink -right-16 -top-20" /><div className="relative flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-pink/30 bg-pink/15 shadow-[0_0_28px_rgba(236,72,153,0.16)]"><Compass className="h-6 w-6 text-pink" /></div><div><div className="mb-1 flex flex-wrap items-center gap-2"><Badge className="border-pink/30 bg-pink/15 text-pink">Direction finder</Badge><span className="text-xs uppercase tracking-[0.2em] text-muted-foreground">AI planning</span></div><h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Career Path Planner</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Compare plausible next steps from your current experience toward a target role.</p></div></div></div>
    <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4"><TabsList className="glass-card flex max-w-full overflow-x-auto p-1"><TabsTrigger value="planner">Planner</TabsTrigger><TabsTrigger value="history"><History className="mr-2 h-4 w-4" />History</TabsTrigger></TabsList>
      <TabsContent value="planner" className="space-y-4"><Card className="glass-card glass-card-hover border-0 shadow-[0_16px_60px_rgba(236,72,153,0.07)]"><CardHeader><CardTitle className="flex items-center gap-2"><Waypoints className="h-5 w-5 text-pink" />Map your next career move</CardTitle><CardDescription>Use a real resume and target role. The suggestions are planning aids, not guarantees of outcomes.</CardDescription></CardHeader><CardContent className="space-y-4"><Input value={targetRole} onChange={(event) => setTargetRole(event.target.value)} placeholder="Target role — e.g. Engineering Manager" className="glass-input" /><Textarea value={resumeContent} onChange={(event) => setResumeContent(event.target.value)} placeholder="Paste your resume content so the paths reflect your current skills..." className="glass-input min-h-[190px]" /><div className="flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{resumeContent.length} characters</span><Button onClick={predict} disabled={predictMutation.isPending} className="btn-glow bg-primary text-primary-foreground">{predictMutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}Generate roadmap</Button></div></CardContent></Card>
        {result && <div className="space-y-4"><Card className="glass-card border-0 border-pink/20"><CardHeader><CardTitle className="text-lg">Three paths to explore</CardTitle><CardDescription>{result.keyInsights.join(" ")}</CardDescription></CardHeader><CardContent><div className="grid gap-3 lg:grid-cols-3">{result.paths.map((path, index) => <div key={`${path.name}-${index}`} className={`rounded-xl border p-4 transition-colors ${index === result.recommendedPath ? "border-pink/50 bg-pink/10 shadow-[0_10px_30px_rgba(236,72,153,0.08)]" : "border-border/60 bg-accent/10 hover:border-pink/25"}`}><div className="flex items-start justify-between gap-2"><h3 className="font-semibold text-foreground">{path.name}</h3>{index === result.recommendedPath && <Badge className="border-pink/30 bg-pink/15 text-pink">Recommended</Badge>}</div><p className="mt-2 text-xs text-muted-foreground">Estimated fit: {path.probability}</p><div className="mt-4 space-y-2">{path.steps.slice(0, 3).map((step, stepIndex) => <div key={`${step.title}-${stepIndex}`} className="flex gap-2"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-pink/15 text-xs text-pink">{stepIndex + 1}</span><div><p className="text-sm font-medium text-foreground">{step.title}</p><p className="text-xs text-muted-foreground">{step.timeline}</p></div></div>)}</div></div>)}</div></CardContent></Card>
          <Card className="glass-card glass-card-hover border-0"><CardHeader><CardTitle className="text-base">Detailed roadmap</CardTitle></CardHeader><CardContent className="space-y-5">{(result.paths[result.recommendedPath] ?? result.paths[0])?.steps.map((step, index) => <div key={`${step.title}-${index}`} className="relative flex gap-4"><div className="flex flex-col items-center"><span className="z-10 flex h-8 w-8 items-center justify-center rounded-full bg-pink/15 text-sm font-semibold text-pink">{index + 1}</span>{index < ((result.paths[result.recommendedPath] ?? result.paths[0])?.steps.length ?? 0) - 1 && <span className="h-full w-px bg-pink/20" />}</div><div className="pb-5"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium text-foreground">{step.title}</h3><Badge variant="outline" className="text-xs">{step.timeline}</Badge></div><p className="mt-1 text-sm leading-relaxed text-muted-foreground">{step.description}</p><div className="mt-2 flex flex-wrap gap-1.5">{step.skills.map((skill) => <Badge key={skill} variant="secondary" className="text-xs text-pink">{skill}</Badge>)}</div></div></div>)}</CardContent></Card><div className="flex justify-end"><ReportActions title="ResumeIQ Career Roadmap" filename="resumeiq-career-roadmap.txt" content={`Target role: ${targetRole}\n\nKey insights: ${result.keyInsights.join(" ")}\n\nPaths:\n${result.paths.map((path, index) => `${index + 1}. ${path.name} (${path.probability})\n${path.steps.map((step) => `  - ${step.title} — ${step.timeline}: ${step.description}`).join("\n")}`).join("\n\n")}`} /></div></div>}
        {!result && !predictMutation.isPending && <div className="rounded-xl border border-dashed border-border/70 bg-accent/5 p-10 text-center"><Compass className="mx-auto mb-3 h-10 w-10 text-muted-foreground/50" /><p className="text-sm text-muted-foreground">Add your target and resume to see a visual path comparison.</p></div>}
      </TabsContent>
      <TabsContent value="history"><Card className="glass-card border-0"><CardHeader><CardTitle>Path history</CardTitle><CardDescription>Reopen a previous roadmap without starting over.</CardDescription></CardHeader><CardContent>{historyQuery.isLoading ? <div className="flex justify-center py-10"><Loader2 className="h-6 w-6 animate-spin text-pink" /></div> : historyQuery.isError ? <p className="rounded-xl bg-rose-400/10 p-4 text-sm text-rose-300">History is temporarily unavailable.</p> : historyQuery.data && historyQuery.data.length > 0 ? <div className="space-y-3">{historyQuery.data.map((item) => <button key={item.id} type="button" onClick={() => { const parsed = safeParse<CareerResult>(item.predictedPaths); if (parsed) { setResult(parsed); setTargetRole(item.targetRole); setResumeContent(""); setActiveTab("planner"); } else toast.error("This saved roadmap could not be opened."); }} className="flex w-full items-center justify-between rounded-xl border border-border/60 bg-accent/10 p-4 text-left hover:border-pink/30"><div><p className="font-medium text-foreground">{item.targetRole}</p><p className="text-xs text-muted-foreground">{new Date(item.createdAt).toLocaleString()}</p></div><ArrowRight className="h-4 w-4 text-pink" /></button>)}</div> : <div className="py-10 text-center text-sm text-muted-foreground"><CheckCircle2 className="mx-auto mb-3 h-9 w-9 opacity-40" /><p>No career paths yet.</p></div>}</CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}
