import { useEffect } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";
import { Flame, Loader2, Medal, RefreshCw, Sparkles, Target, Trophy, Zap } from "lucide-react";

const badgeMeta: Record<string, { label: string; description: string }> = {
  rising_star: { label: "Rising star", description: "Reached level 2" },
  streak_3: { label: "3-day streak", description: "Stayed active for three days" },
  streak_7: { label: "7-day streak", description: "Stayed active for a full week" },
  badge_collector: { label: "Badge collector", description: "Earned three badges" },
  power_user: { label: "Power user", description: "Earned 200 XP" },
  career_master: { label: "Career master", description: "Earned 500 XP" },
};

export default function Gamification() {
  const progressQuery = trpc.progress.get.useQuery();
  const leaderboardQuery = trpc.progress.leaderboard.useQuery();
  const refreshMutation = trpc.progress.refreshStreak.useMutation({
    onSuccess: () => { toast.success("Daily activity refreshed."); void progressQuery.refetch(); void leaderboardQuery.refetch(); },
    onError: (error) => toast.error(error.message || "Could not refresh your streak."),
  });
  useEffect(() => { if (progressQuery.data && progressQuery.data.lastActiveDate !== new Date().toISOString().split("T")[0]) refreshMutation.mutate(); }, [progressQuery.data?.lastActiveDate]);
  const progress = progressQuery.data;
  const badges = progress?.badges ? (() => { try { return JSON.parse(progress.badges) as string[]; } catch { return []; } })() : [];
  const xp = progress?.totalXP ?? 0;
  const level = progress?.level ?? 1;
  const levelStart = (level - 1) * 100;
  const levelProgress = Math.min(100, Math.max(0, ((xp - levelStart) / 100) * 100));

  return <div className="space-y-6">
    <div className="relative overflow-hidden rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5 sm:p-6"><div className="aurora-orb aurora-orb-pink -right-16 -top-20" /><div className="relative flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-amber-400/30 bg-amber-400/15 shadow-[0_0_28px_rgba(251,191,36,0.16)]"><Trophy className="h-6 w-6 text-amber-400" /></div><div><div className="mb-1 flex flex-wrap items-center gap-2"><Badge className="border-amber-400/30 bg-amber-400/15 text-amber-300">Progress hub</Badge><span className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Real activity</span></div><h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Career Momentum</h1><p className="mt-1 text-sm text-muted-foreground">Build a consistent practice habit and see your progress compound.</p></div></div><Button variant="outline" className="glass-input self-start sm:self-auto" onClick={() => refreshMutation.mutate()} disabled={refreshMutation.isPending}><RefreshCw className={`mr-2 h-4 w-4 ${refreshMutation.isPending ? "animate-spin" : ""}`} />Refresh today</Button></div></div>
    {progressQuery.isLoading ? <div className="flex justify-center py-20"><Loader2 className="h-7 w-7 animate-spin text-amber-400" /></div> : progressQuery.isError ? <div className="rounded-xl bg-rose-400/10 p-5 text-sm text-rose-300">Your progress is temporarily unavailable. Refresh to try again.</div> : <>
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4 sm:gap-4"><Card className="glass-card glass-card-hover min-w-0 border-0"><CardContent className="p-4 sm:p-5"><Zap className="h-5 w-5 text-cyan" /><p className="mt-4 text-xs uppercase tracking-wider text-muted-foreground">Total XP</p><p className="mt-1 text-3xl font-bold text-foreground">{xp}</p></CardContent></Card><Card className="glass-card glass-card-hover min-w-0 border-0"><CardContent className="p-4 sm:p-5"><Medal className="h-5 w-5 text-violet" /><p className="mt-4 text-xs uppercase tracking-wider text-muted-foreground">Level</p><p className="mt-1 text-3xl font-bold text-foreground">{level}</p></CardContent></Card><Card className="glass-card glass-card-hover min-w-0 border-0"><CardContent className="p-4 sm:p-5"><Flame className="h-5 w-5 text-orange-400" /><p className="mt-4 text-xs uppercase tracking-wider text-muted-foreground">Current streak</p><p className="mt-1 text-3xl font-bold text-foreground">{progress?.currentStreak ?? 0}<span className="text-sm font-normal text-muted-foreground"> days</span></p></CardContent></Card><Card className="glass-card glass-card-hover min-w-0 border-0"><CardContent className="p-4 sm:p-5"><Target className="h-5 w-5 text-pink" /><p className="mt-4 text-xs uppercase tracking-wider text-muted-foreground">Tasks completed</p><p className="mt-1 text-3xl font-bold text-foreground">{progress?.tasksCompleted ?? 0}</p></CardContent></Card></div>
      <div className="grid gap-4 lg:grid-cols-[1fr_1fr]"><Card className="glass-card glass-card-hover border-0"><CardHeader><CardTitle className="flex items-center justify-between text-lg"><span>Next level</span><span className="text-sm font-normal text-muted-foreground">{Math.max(0, level * 100 - xp)} XP to go</span></CardTitle><CardDescription>Complete career tasks to earn XP and unlock badges.</CardDescription></CardHeader><CardContent><Progress value={levelProgress} className="h-3" /><div className="mt-3 flex justify-between text-xs text-muted-foreground"><span>Level {level}</span><span>Level {level + 1}</span></div></CardContent></Card><Card className="glass-card glass-card-hover border-0"><CardHeader><CardTitle className="text-lg">Longest streak</CardTitle><CardDescription>Your best consistency run so far.</CardDescription></CardHeader><CardContent><p className="text-4xl font-bold text-orange-400">{progress?.longestStreak ?? 0}<span className="ml-2 text-base font-normal text-muted-foreground">days</span></p><div className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><Flame className="h-4 w-4 text-orange-400" />Keep opening a tool each day to maintain momentum.</div></CardContent></Card></div>
      <div className="grid gap-4 lg:grid-cols-[0.9fr_1.1fr]"><Card className="glass-card glass-card-hover border-0"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Medal className="h-5 w-5 text-violet" />Badges</CardTitle><CardDescription>Badges are earned from real activity in your account.</CardDescription></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2">{Object.entries(badgeMeta).map(([key, meta]) => { const earned = badges.includes(key); return <div key={key} className={`rounded-xl border p-3 ${earned ? "border-violet/40 bg-violet/10 shadow-[0_8px_24px_rgba(139,92,246,0.08)]" : "border-border/60 bg-accent/5 opacity-60"}`}><div className="flex items-center gap-2"><div className={`flex h-8 w-8 items-center justify-center rounded-full ${earned ? "bg-violet/20 text-violet" : "bg-accent/30 text-muted-foreground"}`}><Medal className="h-4 w-4" /></div><div><p className="text-sm font-medium text-foreground">{meta.label}</p><p className="text-xs text-muted-foreground">{meta.description}</p></div></div>{earned && <Badge variant="secondary" className="mt-2 text-violet">Earned</Badge>}</div>})}</div></CardContent></Card><Card className="glass-card glass-card-hover border-0"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Trophy className="h-5 w-5 text-amber-400" />Leaderboard</CardTitle><CardDescription>Rankings reflect saved progress, not fabricated demo accounts.</CardDescription></CardHeader><CardContent>{leaderboardQuery.isLoading ? <div className="flex justify-center py-8"><Loader2 className="h-5 w-5 animate-spin text-amber-400" /></div> : leaderboardQuery.isError ? <p className="rounded-xl bg-rose-400/10 p-4 text-sm text-rose-300">Leaderboard is temporarily unavailable.</p> : leaderboardQuery.data && leaderboardQuery.data.length > 0 ? <div className="space-y-2">{leaderboardQuery.data.map((entry) => <div key={entry.userId} className="flex items-center gap-3 rounded-xl border border-border/60 bg-accent/10 p-3"><span className={`flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold ${entry.rank === 1 ? "bg-amber-400/20 text-amber-300" : "bg-accent/30 text-muted-foreground"}`}>{entry.rank}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-foreground">{entry.displayName}</p><p className="text-xs text-muted-foreground">Level {entry.level} · {entry.currentStreak} day streak · {entry.tasksCompleted} tasks</p></div><span className="text-sm font-semibold text-cyan">{entry.totalXP} XP</span></div>)}</div> : <div className="py-8 text-center text-sm text-muted-foreground"><Sparkles className="mx-auto mb-3 h-8 w-8 opacity-40" /><p>Leaderboard appears after progress is recorded.</p></div>}</CardContent></Card></div>
    </>}
  </div>;
}
