import { useState, useRef } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import {
  FileDown,
  FileText,
  Loader2,
  Trash2,
  Eye,
  Download,
  Plus,
  Layers,
  Palette,
  BarChart3,
  FileBarChart,
} from "lucide-react";

const TEMPLATES = [
  { id: "modern", name: "Modern", description: "Clean and professional with accent colors" },
  { id: "classic", name: "Classic", description: "Traditional resume layout" },
  { id: "minimal", name: "Minimal", description: "Simple and elegant typography" },
];

export default function PDFExport() {
  const [activeTab, setActiveTab] = useState("export");
  const [exportType, setExportType] = useState<"resume" | "career_report">("resume");
  const [resumeName, setResumeName] = useState("");
  const [resumeContent, setResumeContent] = useState("");
  const [selectedTemplate, setSelectedTemplate] = useState("modern");
  const [previewHtml, setPreviewHtml] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const previewRef = useRef<HTMLDivElement>(null);

  const utils = trpc.useUtils();

  const saveMutation = trpc.pdfExport.saveResumeVersion.useMutation({
    onSuccess: () => {
      toast.success("Resume version saved!");
      void utils.pdfExport.getVersions.invalidate();
    },
    onError: (err: any) => {
      toast.error(err.message || "Failed to save resume version.");
    },
  });

  const deleteMutation = trpc.resumeVersions.delete.useMutation({
    onSuccess: () => {
      toast.success("Version deleted.");
      void utils.pdfExport.getVersions.invalidate();
    },
    onError: () => {
      toast.error("Failed to delete version.");
    },
  });

  const generateReportMutation = trpc.pdfExport.generateReport.useMutation({
    onSuccess: (data) => {
      setPreviewHtml(data.html);
      toast.success(`${exportType === "career_report" ? "Career report" : "Resume"} generated!`);
    },
    onError: (err: any) => {
      toast.error(err.message || "Failed to generate report.");
    },
  });

  const versionsQuery = trpc.pdfExport.getVersions.useQuery();

  const handleSaveVersion = () => {
    if (!resumeName || !resumeContent) {
      toast.error("Please provide a name and content for your resume.");
      return;
    }
    saveMutation.mutate({ name: resumeName, content: resumeContent });
  };

  const generatePreview = () => {
    if (exportType === "career_report") {
      generateReportMutation.mutate({ type: "career_report" });
      return;
    }

    const accentColors: Record<string, string> = {
      modern: "#06b6d4",
      classic: "#1e293b",
      minimal: "#6366f1",
    };
    const accent = accentColors[selectedTemplate] || "#06b6d4";

    const html = `
      <div style="font-family: 'Inter', sans-serif; max-width: 800px; padding: 40px; color: #e2e8f0; background: #0f172a;">
        <div style="border-bottom: 3px solid ${accent}; padding-bottom: 20px; margin-bottom: 30px;">
          <h1 style="font-size: 28px; color: #f8fafc; margin: 0;">${resumeName || "My Resume"}</h1>
          <p style="color: #94a3b8; font-size: 14px; margin-top: 8px;">Generated by ResumeIQ Pro</p>
        </div>
        <div style="white-space: pre-wrap; line-height: 1.8; font-size: 14px; color: #cbd5e1;">
          ${resumeContent.replace(/</g, '&lt;').replace(/>/g, '&gt;')}
        </div>
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #334155; text-align: center;">
          <p style="font-size: 12px; color: #64748b;">ResumeIQ Pro — AI-Powered Career Intelligence</p>
        </div>
      </div>
    `;
    setPreviewHtml(html);
  };

  const handleExportPDF = async () => {
    if (!previewHtml) {
      toast.error("Please generate a preview first.");
      return;
    }
    setIsGenerating(true);
    try {
      // Lazy import html2pdf to avoid bundle crash
      const html2pdfModule = await import("html2pdf.js");
      const html2pdf = html2pdfModule.default;

      const element = document.createElement("div");
      element.innerHTML = previewHtml;

      const opt: any = {
        margin: 0,
        filename: exportType === "career_report"
          ? `career-report-${new Date().toISOString().split("T")[0]}.pdf`
          : `${resumeName || "resume"}-${selectedTemplate}.pdf`,
        image: { type: "jpeg" as const, quality: 0.98 },
        html2canvas: { scale: 2, backgroundColor: "#ffffff" },
        jsPDF: { unit: "mm" as const, format: "a4" as const, orientation: "portrait" as const },
      };

      await html2pdf().from(element).set(opt).save();
      toast.success("PDF exported successfully!");
    } catch {
      toast.error("Failed to generate PDF.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <div className="w-12 h-12 rounded-xl bg-rose/15 border border-rose/20 flex items-center justify-center">
          <FileDown className="h-6 w-6 text-pink" />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-foreground">PDF Export</h1>
          <p className="text-sm text-muted-foreground">
            Export your resume and career reports as polished PDFs
          </p>
        </div>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4">
        <TabsList className="glass-card p-1">
          <TabsTrigger value="export" className="data-[state=active]:bg-primary/20 data-[state=active]:text-primary">
            <FileDown className="mr-2 h-4 w-4" />
            Export
          </TabsTrigger>
          <TabsTrigger value="versions" className="data-[state=active]:bg-primary/20 data-[state=active]:text-primary">
            <Layers className="mr-2 h-4 w-4" />
            Versions
          </TabsTrigger>
        </TabsList>

        {/* Export Tab */}
        <TabsContent value="export" className="space-y-4">
          <div className="flex gap-3">
            <Button
              variant={exportType === "resume" ? "default" : "outline"}
              onClick={() => { setExportType("resume"); setPreviewHtml(""); }}
              className={`${exportType === "resume" ? "bg-primary text-primary-foreground" : "glass-input"}`}
            >
              <FileText className="mr-2 h-4 w-4" />
              Resume
            </Button>
            <Button
              variant={exportType === "career_report" ? "default" : "outline"}
              onClick={() => { setExportType("career_report"); setPreviewHtml(""); }}
              className={`${exportType === "career_report" ? "bg-primary text-primary-foreground" : "glass-input"}`}
            >
              <BarChart3 className="mr-2 h-4 w-4" />
              Career Report
            </Button>
          </div>

          {exportType === "resume" ? (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              <Card className="glass-card border-0 overflow-hidden">
                <CardHeader>
                  <CardTitle className="text-base">Resume Content</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <Input
                    value={resumeName}
                    onChange={(e) => setResumeName(e.target.value)}
                    placeholder="Resume name (e.g., Senior Dev 2024)"
                    className="glass-input"
                  />
                  <Textarea
                    value={resumeContent}
                    onChange={(e) => setResumeContent(e.target.value)}
                    placeholder="Paste your full resume content here..."
                    className="glass-input min-h-[300px] font-mono text-sm"
                  />
                  <div className="flex gap-2">
                    <Select value={selectedTemplate} onValueChange={setSelectedTemplate}>
                      <SelectTrigger className="glass-input flex-1">
                        <Palette className="mr-2 h-4 w-4 text-violet" />
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="glass-card">
                        {TEMPLATES.map((t) => (
                          <SelectItem key={t.id} value={t.id}>
                            <div>
                              <p className="font-medium">{t.name}</p>
                              <p className="text-xs text-muted-foreground">{t.description}</p>
                            </div>
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    <Button
                      variant="outline"
                      onClick={() => saveMutation.mutate({ name: resumeName || "Untitled", content: resumeContent })}
                      disabled={!resumeName || !resumeContent}
                      className="glass-input"
                    >
                      <Plus className="mr-1 h-4 w-4" />
                      Save
                    </Button>
                  </div>
                  <Button
                    onClick={generatePreview}
                    disabled={!resumeContent}
                    variant="outline"
                    className="glass-input w-full"
                  >
                    <Eye className="mr-2 h-4 w-4" />
                    Generate Preview
                  </Button>
                </CardContent>
              </Card>

              <Card className="glass-card border-0 overflow-hidden">
                <CardHeader className="flex flex-row items-center justify-between">
                  <CardTitle className="text-base">Preview</CardTitle>
                  {previewHtml && (
                    <Button
                      onClick={handleExportPDF}
                      disabled={isGenerating}
                      className="bg-primary text-primary-foreground btn-glow"
                      size="sm"
                    >
                      {isGenerating ? (
                        <>
                          <Loader2 className="mr-2 h-3 w-3 animate-spin" />
                          Generating...
                        </>
                      ) : (
                        <>
                          <Download className="mr-2 h-3 w-3" />
                          Export PDF
                        </>
                      )}
                    </Button>
                  )}
                </CardHeader>
                <CardContent>
                  {previewHtml ? (
                    <div
                      ref={previewRef}
                      className="rounded-lg border border-accent/20 overflow-hidden"
                      dangerouslySetInnerHTML={{ __html: previewHtml }}
                    />
                  ) : (
                    <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                      <Eye className="h-10 w-10 mb-3 opacity-40" />
                      <p className="text-sm">Generate a preview to see your resume</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          ) : (
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
              <Card className="glass-card border-0 overflow-hidden">
                <CardHeader>
                  <CardTitle className="text-base flex items-center gap-2">
                    <FileBarChart className="h-4 w-4 text-violet" />
                    Career Intelligence Report
                  </CardTitle>
                  <CardDescription>
                    Generate a comprehensive career report using all your analysis data.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="p-4 rounded-lg bg-accent/20 space-y-2">
                    <p className="text-sm text-foreground font-medium">Report Includes:</p>
                    <ul className="text-xs text-muted-foreground space-y-1">
                      <li>Profile summary with XP, level, and streak</li>
                      <li>ATS score history and trends</li>
                      <li>Job-fit analysis results</li>
                      <li>Resume improvement history</li>
                      <li>Skill gap analysis summaries</li>
                    </ul>
                  </div>
                  <Button
                    onClick={generatePreview}
                    disabled={generateReportMutation.isPending}
                    className="btn-glow bg-primary text-primary-foreground w-full"
                  >
                    {generateReportMutation.isPending ? (
                      <>
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        Generating Report...
                      </>
                    ) : (
                      <>
                        <FileBarChart className="mr-2 h-4 w-4" />
                        Generate Career Report
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>

              <Card className="glass-card border-0 overflow-hidden">
                <CardHeader className="flex flex-row items-center justify-between">
                  <CardTitle className="text-base">Report Preview</CardTitle>
                  {previewHtml && (
                    <Button
                      onClick={handleExportPDF}
                      disabled={isGenerating}
                      className="bg-primary text-primary-foreground btn-glow"
                      size="sm"
                    >
                      {isGenerating ? (
                        <>
                          <Loader2 className="mr-2 h-3 w-3 animate-spin" />
                          Generating...
                        </>
                      ) : (
                        <>
                          <Download className="mr-2 h-3 w-3" />
                          Export PDF
                        </>
                      )}
                    </Button>
                  )}
                </CardHeader>
                <CardContent>
                  {generateReportMutation.isPending ? (
                    <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                      <Loader2 className="h-8 w-8 animate-spin mb-3" />
                      <p className="text-sm">Generating your career report...</p>
                    </div>
                  ) : previewHtml ? (
                    <div
                      ref={previewRef}
                      className="rounded-lg border border-accent/20 overflow-hidden max-h-[600px] overflow-y-auto"
                      dangerouslySetInnerHTML={{ __html: previewHtml }}
                    />
                  ) : (
                    <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                      <FileBarChart className="h-10 w-10 mb-3 opacity-40" />
                      <p className="text-sm">Generate a career report to preview it</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          )}
        </TabsContent>

        {/* Versions Tab */}
        <TabsContent value="versions" className="space-y-4">
          <Card className="glass-card border-0 overflow-hidden">
            <CardHeader>
              <CardTitle className="text-lg">Resume Versions</CardTitle>
              <CardDescription>
                All your saved resume versions with ATS scores
              </CardDescription>
            </CardHeader>
            <CardContent>
              {versionsQuery.isLoading ? (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
                </div>
              ) : versionsQuery.data && versionsQuery.data.length > 0 ? (
                <div className="space-y-3">
                  {versionsQuery.data.map((version: any) => (
                    <div key={version.id} className="glass-card p-4 flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-lg bg-cyan/20 flex items-center justify-center">
                          <FileText className="h-5 w-5 text-cyan" />
                        </div>
                        <div>
                          <p className="text-sm font-medium text-foreground">{version.name}</p>
                          <div className="flex items-center gap-2">
                            <p className="text-xs text-muted-foreground">
                              {new Date(version.createdAt).toLocaleDateString()}
                            </p>
                            {version.atsScore > 0 && (
                              <Badge variant="secondary" className="text-xs">
                                ATS: {version.atsScore}
                              </Badge>
                            )}
                          </div>
                        </div>
                      </div>
                      <div className="flex gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setResumeName(version.name);
                            setResumeContent(version.content);
                            setActiveTab("export");
                            setExportType("resume");
                            toast.success("Loaded into editor.");
                          }}
                          className="text-muted-foreground hover:text-foreground"
                        >
                          <Eye className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => deleteMutation.mutate({ id: version.id })}
                          className="text-rose-400 hover:text-rose-300"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="text-center py-8 text-muted-foreground">
                  <Layers className="h-10 w-10 mx-auto mb-3 opacity-40" />
                  <p className="text-sm">No saved versions yet. Save your first resume version.</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
