import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { toast } from "sonner";
import { ArrowLeftRight, CalendarDays, FileText, History, Loader2, Trash2, Trophy } from "lucide-react";

type Version = { id: number; name: string; content: string; atsScore: number; jobFitScore: number | null; createdAt: Date };

export default function ResumeVersionManager() {
  const [activeTab, setActiveTab] = useState("versions");
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const versionsQuery = trpc.resumeVersions.list.useQuery();
  const utils = trpc.useUtils();
  const deleteMutation = trpc.resumeVersions.delete.useMutation({
    onSuccess: () => { toast.success("Resume version deleted."); void utils.resumeVersions.list.invalidate(); setSelectedIds([]); },
    onError: (error) => toast.error(error.message || "Could not delete this version."),
  });
  const versions = (versionsQuery.data ?? []) as Version[];
  const selected = useMemo(() => selectedIds.map((id) => versions.find((version) => version.id === id)).filter(Boolean) as Version[], [selectedIds, versions]);

  const toggleSelection = (id: number) => {
    setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 2 ? [...current, id] : [current[1], id]);
  };
  const deleteVersion = (version: Version) => {
    if (window.confirm(`Delete “${version.name}”? This cannot be undone.`)) deleteMutation.mutate({ id: version.id });
  };

  return <div className="space-y-6">
    <div className="relative overflow-hidden rounded-2xl border border-violet/20 bg-violet/5 p-5 sm:p-6"><div className="aurora-orb aurora-orb-violet -right-16 -top-20" /><div className="relative flex items-start gap-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl border border-violet/30 bg-violet/15 shadow-[0_0_28px_rgba(139,92,246,0.16)]"><ArrowLeftRight className="h-6 w-6 text-violet" /></div><div><div className="mb-1 flex flex-wrap items-center gap-2"><Badge className="border-violet/30 bg-violet/15 text-violet">Iteration studio</Badge><span className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Compare with confidence</span></div><h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Resume Version Manager</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Keep iterations organized and compare ATS performance before you apply.</p></div></div></div>
    <Tabs value={activeTab} onValueChange={setActiveTab} className="space-y-4"><TabsList className="glass-card flex max-w-full overflow-x-auto p-1"><TabsTrigger value="versions">Saved versions</TabsTrigger><TabsTrigger value="compare"><ArrowLeftRight className="mr-2 h-4 w-4" />Compare ({selected.length}/2)</TabsTrigger><TabsTrigger value="history"><History className="mr-2 h-4 w-4" />Guidance</TabsTrigger></TabsList>
      <TabsContent value="versions"><Card className="glass-card glass-card-hover border-0 shadow-[0_16px_60px_rgba(139,92,246,0.07)]"><CardHeader><CardTitle>Choose two versions to compare</CardTitle><CardDescription>Versions are created from the PDF Export or ATS Scanner flows and remain private to your account.</CardDescription></CardHeader><CardContent>{versionsQuery.isLoading ? <div className="flex justify-center py-10"><Loader2 className="h-6 w-6 animate-spin text-violet" /></div> : versionsQuery.isError ? <div className="rounded-xl bg-rose-400/10 p-4 text-sm text-rose-300">Unable to load your saved versions. Try refreshing the page.</div> : versions.length > 0 ? <div className="grid gap-3">{versions.map((version) => { const isSelected = selectedIds.includes(version.id); return <div key={version.id} className={`flex flex-col gap-4 rounded-xl border p-4 transition-all sm:flex-row sm:items-center sm:justify-between ${isSelected ? "border-violet/50 bg-violet/10 shadow-[0_10px_30px_rgba(139,92,246,0.08)]" : "border-border/60 bg-accent/10 hover:border-violet/25"}`}><button type="button" onClick={() => toggleSelection(version.id)} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${isSelected ? "bg-violet/20 text-violet" : "bg-accent/30 text-muted-foreground"}`}><FileText className="h-5 w-5" /></span><span className="min-w-0"><span className="block truncate font-medium text-foreground">{version.name}</span><span className="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="h-3 w-3" />{new Date(version.createdAt).toLocaleString()}<Badge variant="secondary" className="text-cyan">ATS {version.atsScore}/100</Badge>{version.jobFitScore ? <Badge variant="secondary">Fit {version.jobFitScore}%</Badge> : null}</span></span></button><div className="flex items-center gap-2 sm:shrink-0"><Button variant="outline" className="glass-input" onClick={() => toggleSelection(version.id)}>{isSelected ? "Selected" : "Compare"}</Button><Button variant="ghost" size="icon" aria-label={`Delete ${version.name}`} onClick={() => deleteVersion(version)} disabled={deleteMutation.isPending} className="text-rose-300 hover:bg-rose-400/10 hover:text-rose-200"><Trash2 className="h-4 w-4" /></Button></div></div>})}</div> : <div className="py-12 text-center text-sm text-muted-foreground"><FileText className="mx-auto mb-3 h-10 w-10 opacity-40" /><p>No saved resume versions yet.</p><p className="mt-1">Save a version from ATS Scanner or PDF Export to begin comparing.</p></div>}</CardContent></Card></TabsContent>
      <TabsContent value="compare">{selected.length === 2 ? <div className="space-y-4"><div className="grid gap-4 lg:grid-cols-2">{selected.map((version) => <Card key={version.id} className="glass-card border-0"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle className="text-lg">{version.name}</CardTitle><CardDescription>{new Date(version.createdAt).toLocaleDateString()}</CardDescription></div><Badge className="bg-violet/15 text-violet">ATS {version.atsScore}/100</Badge></div></CardHeader><CardContent><pre className="max-h-[420px] overflow-auto whitespace-pre-wrap rounded-xl bg-background/40 p-4 font-sans text-sm leading-relaxed text-muted-foreground">{version.content}</pre></CardContent></Card>)}</div><Card className="glass-card border-0"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Trophy className="h-4 w-4 text-amber-400" />Comparison summary</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2">{selected.map((version) => <div key={version.id} className="rounded-xl border border-border/60 bg-accent/10 p-4"><p className="truncate text-sm font-medium text-foreground">{version.name}</p><p className="mt-2 text-2xl font-bold text-cyan">{version.atsScore}<span className="text-sm text-muted-foreground">/100 ATS</span></p>{version.jobFitScore ? <p className="mt-1 text-xs text-muted-foreground">Job fit: {version.jobFitScore}%</p> : null}</div>)}</div></CardContent></Card></div> : <div className="rounded-xl border border-dashed border-border/70 bg-accent/5 p-12 text-center"><ArrowLeftRight className="mx-auto mb-3 h-10 w-10 text-muted-foreground/50" /><p className="text-sm text-muted-foreground">Select exactly two saved versions from the Saved versions tab to compare them side-by-side.</p><Button variant="outline" className="glass-input mt-4" onClick={() => setActiveTab("versions")}>Choose versions</Button></div>}</TabsContent>
      <TabsContent value="history"><Card className="glass-card border-0"><CardHeader><CardTitle className="text-lg">A simple versioning habit</CardTitle><CardDescription>Use names that make decisions easy later.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-3">{[{ title: "Name by target", body: "Use a role or company label so the right resume is easy to find." }, { title: "Scan before saving", body: "Save the version after an ATS scan to preserve its score." }, { title: "Compare, then apply", body: "Use the higher-scoring draft as a signal, then proofread for accuracy." }].map((item) => <div key={item.title} className="rounded-xl border border-border/60 bg-accent/10 p-4"><p className="font-medium text-foreground">{item.title}</p><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{item.body}</p></div>)}</CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}
